version: '3.3'
services:
  #DataBase
  db: 
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: WPD
      MYSQL_USER: Admin
      MYSQL_PASSWORD: admin
    networks:
      - wpsite
  #phpmyadmin
  phpmyadmin: 
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
    - wpsite
  #wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: Admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: WPD
    networks: 
      - wpsite
networks:
  wpsite:
volumes:
  db_data: {}