version: '3'

services:
  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - wordpress
      - mysql
      - phpmyadmin
    restart: always
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    volumes: [db_data:/var/lib/mysql]
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WPD
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wordpress
   #wordpress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: always
    volumes: ['./wordpress:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: WPD
      WORDPRESS_TABLE_PREFIX: wp_
    networks: 
      - wordpress
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
        - "8000:80"
    depends_on: 
        - mysql
    environment: 
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: password
    networks: 
        - wordpress
networks:
  wordpress:
volumes:
  db_data: {}